# Generated by Django 4.2.1 on 2024-11-03 20:20

from django.db import migrations, models
import gcna_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0032_remove_nutmeg_land_parish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land_info',
            old_name='visit',
            new_name='training_add',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='address',
            new_name='parish',
        ),
        migrations.RemoveField(
            model_name='farmer_info',
            name='address',
        ),
        migrations.RemoveField(
            model_name='land_tenur',
            name='No_Legal_Title_comment',
        ),
        migrations.RemoveField(
            model_name='other_seasoning_trees',
            name='Est_Production_Celery',
        ),
        migrations.RemoveField(
            model_name='other_seasoning_trees',
            name='Est_Production_Hot_Pepper',
        ),
        migrations.RemoveField(
            model_name='other_seasoning_trees',
            name='Est_Production_Parsley',
        ),
        migrations.RemoveField(
            model_name='other_seasoning_trees',
            name='Est_Production_Petit_Bum',
        ),
        migrations.RemoveField(
            model_name='other_seasoning_trees',
            name='Est_Production_Seasoning_Pepper',
        ),
        migrations.RemoveField(
            model_name='other_seasoning_trees',
            name='Est_Production_Thyme',
        ),
        migrations.RemoveField(
            model_name='other_seasoning_trees',
            name='Est_Production_chive',
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='COMPLETE',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Is it Complete'),
        ),
        migrations.AddField(
            model_name='nutmeg_land',
            name='parish',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nutmeg_land',
            name='tenurship',
            field=models.CharField(choices=[('', '--Select an option--'), ('Owned', 'Owned'), ('Freehold', 'Freehold'), ('Leased', 'Leased'), ('Family Land', 'Family Land'), ('ShareCrop', 'ShareCrop'), ('Rent', 'Rent'), ('Rented free', 'Rented free'), ('Premission to work land', 'Premission to work land'), ('Squatted', 'Squatted'), ('Government Land', 'Government Land'), ('Other', 'Other'), ('Caretaker', 'Caretaker'), ('Administrator', 'Administrator')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutmeg_land',
            name='village',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_inspection',
            name='Cargo_present_cont',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='citrus_mango_trees',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coconut_trees',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farm_house',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='farm_house',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farm_house',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farm_water_source',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='farm_water_source',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farm_water_source',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer_info',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer_info',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food_safety_and_quality',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='food_safety_and_quality',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food_safety_and_quality',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspector_symmary',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspector_symmary',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspector_symmary',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labour_support',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='acreage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='farm_type',
            field=models.CharField(choices=[('', '--Select an option--'), ('Nutmeg', 'Nutmeg'), ('Coconut', 'Coconut'), ('Other Spices', 'Other Spices')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='parish',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='land_info',
            name='rainfall_pattern',
            field=models.CharField(choices=[('', '--Select an option--'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Mild')], default='P', max_length=100),
        ),
        migrations.AlterField(
            model_name='land_tenur',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='land_tenur',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='land_tenur',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutmeg_frequency',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='nutmeg_frequency',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutmeg_frequency',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutmeg_land',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='nutmeg_land',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutmeg_land',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nutmeg_trees',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nutmeg_variety',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='nutmeg_variety',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutmeg_variety',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='other_crops',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='other_crops',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='other_crops',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='other_crops_cultivated',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='other_crops_cultivated',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='other_crops_cultivated',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='other_seasoning_trees',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='other_spices_trees',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='potential_risks',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='potential_risks',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='potential_risks',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR1_A',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR1_B',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR1_C',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR1_D',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR1_E',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR2_A',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR2_B',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR2_C',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR2_D',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR2_E',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR3_A',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR3_B',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR3_C',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR3_D',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR3_E',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR4_A',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR4_B',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR4_C',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR4_D',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR4_E',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR5_A',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR5_B',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR5_C',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR5_D',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR5_E',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='ASSORTOR6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='Approved_BY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='BATCH_NUMBER',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='BROKEN',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='COMMENTS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='CRACKED',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='DATE_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='DATE_OF_REPORT',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='FOREIGN_MATTER',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='Nutmeg_Assorted',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Sounds', 'Sounds'), ('Lights', 'Lights'), ("110's", "110's"), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='Nutmeg_Assorted2',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Sounds', 'Sounds'), ('Lights', 'Lights'), ("110's", "110's"), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='Nutmeg_Assorted_cont',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='PIECES',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='PINHOLES',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='REWORK',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='SAMPLE_WEIGHT',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='SIGNED_BY_QUALITY_ASSURANCE_OFFICER',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='SOUNDS',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='SUPERVISOR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='SUPERVISOR_A',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='SUPERVISOR_B',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='SUPERVISOR_C',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='SUPERVISOR_D',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='SUPERVISOR_E',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='Station_Manager',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='road_access',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='road_access',
            name='Nutmeg_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='road_access',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='training_support',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Cargo_present',
            field=models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Mace', 'Mace'), ('Nutmeg', 'Nutmeg'), ('Other', 'Other')], default='--Select Provider--', max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='Land_ID_N0',
            field=models.CharField(default=gcna_data.models.land_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='Worker_ID_No',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
