# Generated by Django 4.2.1 on 2024-11-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0033_rename_visit_land_info_training_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_ciontrol',
            name='Nutmeg_Assorted_cont',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='package_ciontrol',
            name='PACKAGING_MATERIAL_cont',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='package_ciontrol',
            name='PRODUCT_DESCRIPTION_cont',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
