# Generated by Django 4.2.1 on 2024-11-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0035_container_inspection_log_day_of_loading_truckentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container_inspection_log',
            name='Date_Of_Inspection',
        ),
        migrations.AddField(
            model_name='container_inspection_log',
            name='Date_Of_Inspectio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Approved',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Container_Condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Container_Condition_st',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Date_Of_Intended_Use',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Date_Of_Loading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='FL_Clean',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='FL_Dry',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='FL_Odors',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='FL_Surface',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Free_From_Dent',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Free_From_Holes',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Free_From_Rust',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='LI_Dry',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='LI_Free_From_Dent',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='LI_Free_From_Holes',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='LI_Free_From_Rust',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Locking_Mech_Func',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='RF_Dry',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='RF_Free_From_Dent',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='RF_Free_From_Holes',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='RF_Free_From_Rust',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='RI_Dry',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='RI_Free_From_Dent',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='RI_Free_From_Holes',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='RI_Free_From_Rust',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Recommend',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Seals_Without_Vents',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Y', 'Y'), ('N', 'N')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Time_Loading_End',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='Time_Loading_Start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='inspected_Date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='container_inspection_log',
            name='reviewed_Date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
