# Generated by Django 4.2.1 on 2024-11-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0036_remove_container_inspection_log_date_of_inspection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container_inspection_log',
            old_name='Date_Of_Inspectio',
            new_name='Date_Of_Inspection',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Absorabant_Used',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Approved',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Bill_Of_Lading',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Container_Condition',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Container_Number',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Container_Size',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Date_Of_Loading',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Fumigant',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Fumigated_By',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Inspected_And_Prepared_By',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Placement',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Port_of_Loading',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Reviewed_By',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Seal_Number',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Time_Loading_End',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='Time_Loading_Start',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='inspected_Date',
        ),
        migrations.RemoveField(
            model_name='day_of_loading',
            name='reviewed_Date',
        ),
        migrations.AlterField(
            model_name='truckentry',
            name='Num_Of_Bags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
