# Generated by Django 4.2.1 on 2025-05-14 16:47

from django.db import migrations, models
import gcna_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0037_rename_date_of_inspectio_container_inspection_log_date_of_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg',
            name='Vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg_rec',
            name='Vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='entryCheck',
            field=models.CharField(default=gcna_data.models.shelf_id, max_length=50),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='BatchCodes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number of Bags'),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='Control_Num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number of Bags'),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='Delivery_Advice_Num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number of Bags'),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='LBS_OF_NUTMEGS_CRACKED',
            field=models.IntegerField(blank=True, default=0, verbose_name='Lbs of Nutmegs cracked'),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='STATION',
            field=models.CharField(blank=True, choices=[('', '--Select Location--'), ('H', 'Beaulieu'), ('M', 'Gouyave'), ('G', 'Grenville')], max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='WAREHOUSE_RECEIPT_NUMBERS',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Warehouse Reciept Number'),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='escape_nutmeg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='fragments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='num_pieces',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='regular_nutmeg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='Station',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave')], max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='Station_rec',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave')], max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_green_nutmeg',
            name='STATION',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave'), ('V', 'Victoria'), ('T', 'Thebaide'), ('HO', 'Head Office')], max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_green_nutmeg_rec',
            name='Station',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave')], max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionGP_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionGP_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionG_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionG_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionH_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionH_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionM_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionM_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionU_heavy',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='SectionU_light',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='APPROX_END_DRYING_DATE',
            field=models.DateField(blank=True, null=True, verbose_name='Approximate end drying date'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='START_DRYING_DATE',
            field=models.DateField(blank=True, null=True, verbose_name='Start drying date'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='STATION',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave'), ('V', 'Victoria'), ('T', 'Thebaide'), ('HO', 'Head Office')], max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='mace_dispatched',
            name='STATION',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave'), ('V', 'Victoria'), ('T', 'Thebaide'), ('HO', 'Head Office')], max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='mace_purchase',
            name='STATION',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave'), ('V', 'Victoria'), ('T', 'Thebaide'), ('HO', 'Head Office')], max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Cargo_present',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Mace', 'Mace'), ('Nutmeg', 'Nutmeg'), ('Other', 'Other')], default='--Select Provider--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Clean_check',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Clean', 'Clean'), ('In need of washing', 'In need of washing')], default='--Select Provider--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Condition_of_cargo',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Dry', 'Dry'), ('Wet', 'Wet')], default='--Select Provider--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Oil_Spill',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50, verbose_name='Oil Spill'),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Presence_of_Debris',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Provider',
            field=models.CharField(choices=[('--Select Provider--', '--Select Provider--'), ('GCNA', 'GCNA'), ('Third_Party', 'Third_Party')], default='--Select Provider--', max_length=50, verbose_name='Packaging Material'),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Resisdue_prev_Cargo',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Tarpaulin_present',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Tyres_fit',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='Weather',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Raining', 'Raining')], default='--Select Provider--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='covered_goods',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='insurance_check',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Decision--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='liscense_check',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Decision--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='vehicle_for_use',
            field=models.CharField(choices=[('--Select Decision--', '--Select Decision--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50),
        ),
    ]
