# Generated by Django 4.2.1 on 2025-12-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0038_dispatch_of_green_nutmeg_vehicle_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floated_moisture_analysis_a',
            name='BATCH_CODE',
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='BATCH_CODE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='BATCH_CODE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='floation_summary',
            name='END_DRYING_DATE',
            field=models.DateField(blank=True, null=True, verbose_name='End drying date'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AddField(
            model_name='floated_moisture_analysis_a',
            name='Batch_Code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
