# Generated by Django 4.2.1 on 2026-01-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0039_remove_floated_moisture_analysis_a_batch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cracking_summary',
            name='STATION',
            field=models.CharField(blank=True, choices=[('', '--Select Location--'), ('B', 'Beaulieu'), ('GP', 'Gouyave'), ('G', 'Grenville')], max_length=50, null=True, verbose_name='Station'),
        ),
    ]
