# Generated by Django 4.2.1 on 2026-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0040_alter_cracking_summary_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mace_purchase',
            name='MACE_1',
            field=models.CharField(max_length=50, verbose_name='Number of Bags'),
        ),
        migrations.AlterField(
            model_name='mace_purchase',
            name='MACE_2',
            field=models.CharField(max_length=50, verbose_name='Number of Bags'),
        ),
        migrations.AlterField(
            model_name='mace_purchase',
            name='MACE_3',
            field=models.CharField(max_length=50, verbose_name='Number of Bags'),
        ),
        migrations.AlterField(
            model_name='mace_purchase',
            name='NUM_OF_BAGS',
            field=models.CharField(max_length=50, verbose_name='Number of Bags'),
        ),
        migrations.AlterField(
            model_name='mace_purchase',
            name='TOTAL_LBS_NUTMEG_BOUGHT',
            field=models.CharField(max_length=50, null=True, verbose_name='Total lbs of nutmeg bought'),
        ),
        migrations.AlterField(
            model_name='mace_purchase',
            name='TOTAL_NUM_OF_FARMERS',
            field=models.CharField(max_length=50, verbose_name='Total Numbers of Farmers'),
        ),
    ]
