# Generated by Django 4.2.1 on 2026-02-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0041_alter_mace_purchase_mace_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_house_drying',
            name='PLACE_OF_PURCHASE',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave'), ('V', 'Victoria'), ('T', 'Thebaide'), ('HO', 'Head Office')], max_length=50, null=True, verbose_name='Place of Purchase '),
        ),
        migrations.AlterField(
            model_name='mace_purchase',
            name='PLACE_OF_PURCHASE',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave'), ('V', 'Victoria'), ('T', 'Thebaide'), ('HO', 'Head Office')], max_length=50, null=True, verbose_name='Place of Purchase '),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='Nutmeg_Assorted',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Sounds', 'Sounds'), ('Lights', 'Lights'), ("110's", "110's"), ("80's/85's", "80's/85's"), ("60's", "60's"), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='Nutmeg_Assorted2',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Sounds', 'Sounds'), ('Lights', 'Lights'), ("110's", "110's"), ("80's/85's", "80's/85's"), ("60's", "60's"), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
